/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAuthenticatorAppDialog: typeof import('./resources/ts/components/dialogs/AddAuthenticatorAppDialog.vue')['default']
    AddEditAddressDialog: typeof import('./resources/ts/components/dialogs/AddEditAddressDialog.vue')['default']
    AddEditPermissionDialog: typeof import('./resources/ts/components/dialogs/AddEditPermissionDialog.vue')['default']
    AddEditRoleDialog: typeof import('./resources/ts/components/dialogs/AddEditRoleDialog.vue')['default']
    AppAutocomplete: typeof import('./resources/ts/@core/components/app-form-elements/AppAutocomplete.vue')['default']
    AppBarSearch: typeof import('./resources/ts/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./resources/ts/@core/components/cards/AppCardActions.vue')['default']
    AppCardCode: typeof import('./resources/ts/@core/components/cards/AppCardCode.vue')['default']
    AppCombobox: typeof import('./resources/ts/@core/components/app-form-elements/AppCombobox.vue')['default']
    AppDateTimePicker: typeof import('./resources/ts/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/ts/@core/components/AppDrawerHeaderSection.vue')['default']
    AppOtpInput: typeof import('./resources/ts/@core/components/app-form-elements/AppOtpInput.vue')['default']
    AppPricing: typeof import('./resources/ts/components/AppPricing.vue')['default']
    AppSearchHeader: typeof import('./resources/ts/components/AppSearchHeader.vue')['default']
    AppSelect: typeof import('./resources/ts/@core/components/app-form-elements/AppSelect.vue')['default']
    AppStepper: typeof import('./resources/ts/@core/components/AppStepper.vue')['default']
    AppTextarea: typeof import('./resources/ts/@core/components/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./resources/ts/@core/components/app-form-elements/AppTextField.vue')['default']
    BuyNow: typeof import('./resources/ts/@core/components/BuyNow.vue')['default']
    CardAddEditDialog: typeof import('./resources/ts/components/dialogs/CardAddEditDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/ts/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/ts/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsVerticalSimple: typeof import('./resources/ts/@core/components/CardStatisticsVerticalSimple.vue')['default']
    ConfirmDialog: typeof import('./resources/ts/components/dialogs/ConfirmDialog.vue')['default']
    CreateAppDialog: typeof import('./resources/ts/components/dialogs/CreateAppDialog.vue')['default']
    CustomCheckboxes: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomCheckboxesWithImage.vue')['default']
    CustomizerSection: typeof import('./resources/ts/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
    DialogCloseBtn: typeof import('./resources/ts/@core/components/DialogCloseBtn.vue')['default']
    EnableOneTimePasswordDialog: typeof import('./resources/ts/components/dialogs/EnableOneTimePasswordDialog.vue')['default']
    ErrorHeader: typeof import('./resources/ts/components/ErrorHeader.vue')['default']
    I18n: typeof import('./resources/ts/@core/components/I18n.vue')['default']
    MoreBtn: typeof import('./resources/ts/@core/components/MoreBtn.vue')['default']
    Notifications: typeof import('./resources/ts/@core/components/Notifications.vue')['default']
    PricingPlanDialog: typeof import('./resources/ts/components/dialogs/PricingPlanDialog.vue')['default']
    ReferAndEarnDialog: typeof import('./resources/ts/components/dialogs/ReferAndEarnDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./resources/ts/@core/components/ScrollToTop.vue')['default']
    ShareProjectDialog: typeof import('./resources/ts/components/dialogs/ShareProjectDialog.vue')['default']
    Shortcuts: typeof import('./resources/ts/@core/components/Shortcuts.vue')['default']
    SnackBar: typeof import('./resources/ts/components/SnackBar/index.vue')['default']
    TheCustomizer: typeof import('./resources/ts/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    TwoFactorAuthDialog: typeof import('./resources/ts/components/dialogs/TwoFactorAuthDialog.vue')['default']
    UserInfoEditDialog: typeof import('./resources/ts/components/dialogs/UserInfoEditDialog.vue')['default']
    UserUpgradePlanDialog: typeof import('./resources/ts/components/dialogs/UserUpgradePlanDialog.vue')['default']
  }
}
